# This will run on Travis' 'new' container-based infrastructure
sudo: false 

# Blacklist
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - graphviz

# Build your code e.g. by calling make
script:
  - doxygen libClearCore/Doc/libClearCore.cfg
  - touch /home/travis/build/Teknic-Inc/ClearCore-library/html/.nojekyll

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
